# Generated by Django 3.1.8 on 2022-01-20 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_auto_20220120_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slides',
            name='image',
            field=models.ImageField(null=True, upload_to='book/%Y/%m', verbose_name='image'),
        ),
        migrations.CreateModel(
            name='VehicleDeatil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(help_text='文章标题', max_length=100)),
                ('description', models.CharField(help_text='文章标题', max_length=100)),
                ('image', models.TextField(help_text='文章正文')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('vehicles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='story.vehicles', verbose_name='Vehicles')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
