# Generated by Django 3.1.8 on 2022-01-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20220120_2346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VehicleDeatil',
            new_name='VehicleDetail',
        ),
    ]
