# Generated by Django 2.2.13 on 2022-01-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_auto_20220121_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slides',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stories',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
