# Generated by Django 2.2.13 on 2022-01-21 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_auto_20220121_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='video',
            field=models.ImageField(null=True, upload_to='video/%Y/%m', verbose_name='video'),
        ),
    ]
