# Generated by Django 2.2.13 on 2022-01-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_auto_20220121_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/%Y/%m', verbose_name='视频内容'),
        ),
    ]
