# Generated by Django 2.2.13 on 2022-01-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_auto_20220121_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='duration_raw',
        ),
    ]
