# Generated by Django 2.2.13 on 2022-01-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0009_remove_stories_duration_raw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slides',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/%Y/%m/%d', verbose_name='视频内容'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d', verbose_name='image'),
        ),
    ]
