# Generated by Django 2.2.13 on 2022-01-21 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0010_auto_20220121_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
