# Generated by Django 2.2.13 on 2022-01-21 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_auto_20220121_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slides',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间'),
        ),
    ]
