# Generated by Django 2.2.13 on 2022-01-24 03:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0013_auto_20220121_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slides',
            options={'ordering': ['-created'], 'verbose_name': '轮播图', 'verbose_name_plural': '轮播图'},
        ),
        migrations.AlterModelOptions(
            name='stories',
            options={'ordering': ['-created'], 'verbose_name': '故事列表', 'verbose_name_plural': '故事列表'},
        ),
        migrations.AlterModelOptions(
            name='vehicledetail',
            options={'ordering': ['-created'], 'verbose_name': '轶事详情', 'verbose_name_plural': '轶事详情'},
        ),
        migrations.AlterModelOptions(
            name='vehicles',
            options={'ordering': ['-created'], 'verbose_name': '轶事列表', 'verbose_name_plural': '轶事列表'},
        ),
        migrations.AlterField(
            model_name='slides',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='slides',
            name='description',
            field=models.CharField(help_text='description', max_length=300, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='slides',
            name='header',
            field=models.CharField(help_text='header', max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='slides',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='slides',
            name='sub_header',
            field=models.CharField(help_text='sub_header', max_length=100, verbose_name='子标题'),
        ),
        migrations.AlterField(
            model_name='slides',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='description',
            field=models.CharField(help_text='description', max_length=100, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='duration',
            field=models.TextField(help_text='duration', null=True, verbose_name='时长'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='header',
            field=models.CharField(help_text='标题', max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d', verbose_name='图片封面'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='original_description',
            field=models.CharField(help_text='original_description', max_length=100, verbose_name='原简介'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='original_header',
            field=models.CharField(help_text='original_header', max_length=100, verbose_name='原标题'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/%Y/%m/%d', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='description',
            field=models.CharField(help_text='description', max_length=100, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='header',
            field=models.CharField(help_text='标题', max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='description',
            field=models.CharField(help_text='description', max_length=100, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='header',
            field=models.CharField(help_text='header', max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='sub_header',
            field=models.CharField(help_text='sub_header', max_length=100, verbose_name='子标题'),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
