# Generated by Django 2.2.13 on 2022-01-24 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0016_auto_20220124_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stories',
            name='images',
        ),
        migrations.AddField(
            model_name='storiedetail',
            name='stories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='story.Stories'),
        ),
    ]
