# Generated by Django 3.1.8 on 2021-11-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_entitie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CharmCode', max_length=32, verbose_name='站点名称')),
                ('site_year', models.CharField(default='2020', max_length=16, verbose_name='年份')),
                ('site_title', models.CharField(default='Just For Fun', max_length=64, verbose_name='站点标题')),
                ('type_chinese', models.CharField(default='向着未来而生', max_length=64, verbose_name='中文座右铭')),
                ('type_english', models.CharField(default='Being toward future', max_length=64, verbose_name='英文左座右铭')),
                ('home_title', models.CharField(default='CharmCode.cn', max_length=64, verbose_name='主页站点')),
                ('my_mail', models.CharField(default='wg_python@163.com', max_length=64, verbose_name='我的邮箱地址')),
                ('site_keywords', models.CharField(default='charmcode.com,代码的魅力,web前端,Python后端,小程序,安卓逆向,Python爬虫,渗透测试', max_length=128, verbose_name='站点描述(meta显示)')),
                ('site_desc', models.CharField(default='领略代码的魅力,分享web前端,html5,css3,Python后端代码分享,了解认知前沿技术', max_length=128, verbose_name='站点描述(meta显示)')),
                ('domain_url', models.CharField(default='https://www.charmcode.cn', max_length=128, verbose_name='站点地址')),
                ('site_avatar', models.CharField(default='https://image.3001.net/images/20200504/1588558613_5eaf7b159c8e9.jpeg', max_length=128, verbose_name='站点地址')),
                ('about_name', models.CharField(default='王小右', max_length=32, verbose_name='about名称')),
                ('about_desc', models.CharField(default='兴趣使然的编程爱好者', max_length=128, verbose_name='about简介')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
    ]
